title: GovEx Labs
description: Our playground for experimentation and fluid content.

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
    scope:
      path: "submodule-test"
    values:
      layout: collaboration
    scope:
      path: "open-data-portal-requirements"
    values:
      layout: collaboration
